-- AlterEnum (additive only - existing CaseAction rows are untouched)
ALTER TYPE "CaseActionType" ADD VALUE IF NOT EXISTS 'CONTACTED_USER';
ALTER TYPE "CaseActionType" ADD VALUE IF NOT EXISTS 'CONTACTED_AUTHORITY';
ALTER TYPE "CaseActionType" ADD VALUE IF NOT EXISTS 'FIELD_VISIT';
ALTER TYPE "CaseActionType" ADD VALUE IF NOT EXISTS 'EVIDENCE_REVIEWED';
ALTER TYPE "CaseActionType" ADD VALUE IF NOT EXISTS 'MEETING_HELD';
ALTER TYPE "CaseActionType" ADD VALUE IF NOT EXISTS 'OTHER_ACTION';
